### ISSUE TITLE
Did it break? Not selecting, just jumping.

### ISSUE THREAD

**Issue by abenz1267** [David-Kunz/treesitter-unit#12] opened 2022-07-15 10:47 UTC
Hi,

did the plugin break? Selecting based on unit doesn't select anymore, but only jumps to the units end. Tried with a minimal config.
I'm on Nvim 0.7.2.

Regards

**Comment by David-Kunz** [comment] 2022-07-15 10:52
Hi @abenz1267 ,

It works for me, also using Neovim 0.7.2.

Is Treesitter correctly configured for your language?

Best regards,
David

**Comment by David-Kunz** [comment] 2022-07-15 10:52
...and which command are you executing exactly?

**Comment by abenz1267** [comment] 2022-07-15 11:05
Hi,

doesn't work in any language for me. That's my keybinds:

```lua
    vim.keymap.set('x', 'iu', tunit.select)
    vim.keymap.set('x', 'au', function() tunit.select(true) end)
    vim.keymap.set('o', 'iu', tunit.select)
    vim.keymap.set('o', 'au', function() tunit.select(true) end)
```

Hm, if it's working for you i assume i did an upsi somewhere. I'll check again.

Regards

**Comment by abenz1267** [comment] 2022-07-15 11:11
So i did a completely fresh nvim config. deleted ALL installed plugins, added treesitter and treesitter-unit manually. this is my whole nvim config now:

```lua
    require'nvim-treesitter.configs'.setup {
        ensure_installed = "all",
        highlight = {enable = true},
        indent = {enable = false},
        incremental_selection = {
            enable = true,
            keymaps = {
                init_selection = "<CR>",
                node_incremental = "<CR>",
                node_decremental = "<BS>"
            }
        },
    }

    -- Treesitter-Unit
    local tunit = require "treesitter-unit"

    vim.keymap.set('x', 'iu', tunit.select)
    vim.keymap.set('x', 'au', function() tunit.select(true) end)
    vim.keymap.set('o', 'iu', tunit.select)
    vim.keymap.set('o', 'au', function() tunit.select(true) end)
```

If i do f.e. `vau` in Go, it just jumps, doesn't select.

Regards

**Comment by David-Kunz** [comment] 2022-07-15 11:15
Interesting, I can reproduce the problem with your config.

What's strange:
If you execute `:lua require'treesitter-unit'.select(true)` it works as expected, but not when done using your keymaps.

**Comment by abenz1267** [comment] 2022-07-15 11:17
Yeah, i also noticed that. I assume it's related to Nvim's new `vim.keymap.set` instead of the deprecated `vim.api.nvim_set_keymap`.

**Comment by David-Kunz** [comment] 2022-07-15 11:21
Yes I assume so too.

Can you try
```lua
vim.keymap.set('x', 'iu', ':<c-u>lua require"treesitter-unit".select()<CR>')
vim.keymap.set('o', 'iu', ':<c-u>lua require"treesitter-unit".select()<CR>')
vim.keymap.set('x', 'au', ':<c-u>lua require"treesitter-unit".select(true)<CR>')
vim.keymap.set('o', 'au', ':<c-u>lua require"treesitter-unit".select(true)<CR>')
```

**Comment by abenz1267** [comment] 2022-07-15 11:25
Yeah that works

**Comment by David-Kunz** [comment] 2022-07-15 11:29
Ok, since this is the official recommendation according to the `README`, I will close this issue. Would be interesting though why the `vim.keymap.set` variant doesn't work. `<c-u>`?

**Closed as completed by David-Kunz** 2022-07-15 11:29 UTC
